#image:
#  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: ignore
  - port: 3000
    onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# Backend can't fetch from DB
tasks:
  - init: cd backend && npm install
    command: npm start
    name: Run back end
  - init: cd frontend && npm install
    command: npm start
    name: Run frontend

#- init: cd frontend && npm install
#    command: npm test
#    name: Run tests
# Cypress tests are not working with gitpod


